[phases.setup]
nixPkgs = ["nodejs_22", "ffmpeg", "python3", "vips", "pkg-config"]

[phases.install]
cmds = [
  "NODE_OPTIONS=--max-old-space-size=1024 npm ci --no-audit --ignore-scripts",
  "npm rebuild sharp --no-audit",
]

[phases.build]
cmds = []

[start]
cmd = "npm run start"
